// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnGo': string;
  'relative': string;
  'settingBtn': string;
  'settingModal': string;
  'toolSpacing': string;
}
export const cssExports: CssExports;
export default cssExports;
