// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    btnGo: string;
    dropOverLeft: string;
    dropOverRight: string;
    hideIcon: string;
    relative: string;
    settingBtn: string;
    settingModal: string;
    th: string;
    toolSpacing: string;
}
export const cssExports: CssExports;
export default cssExports;
