// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'customTreeSelect': string;
  'endExtra': string;
  'flex': string;
  'flex1': string;
  'flexAlign': string;
  'flexColumn': string;
  'flexInline': string;
  'flexRow': string;
  'flexWrap': string;
  'formBtn': string;
  'formCard': string;
  'formCheckbox': string;
  'formCollapse': string;
  'formColon': string;
  'formContainer': string;
  'formHelpAbsolute': string;
  'formHorizon': string;
  'formHorizonAlways': string;
  'formItem': string;
  'formItemBottom': string;
  'formItemClean': string;
  'formItemDefault': string;
  'formItemLarge': string;
  'formItemSmall': string;
  'formNextCard': string;
  'formPwdIcon': string;
  'formRequiredAbsolute': string;
  'formRequiredHide': string;
  'formRow': string;
  'formUnit': string;
  'inlineBlock': string;
  'inputRange': string;
  'inputRangeFocus': string;
  'inputRangeLeft': string;
  'inputRangeRight': string;
  'inputRangeSplit': string;
  'marginNone': string;
  'verticalMiddle': string;
}
export const cssExports: CssExports;
export default cssExports;
